name: PaidWarp
main: com.dmine.PaidWarp.PaidWarp
version: 1.0
description: >
             Allow users to warp to predefined warp points. Warping costs money.
commands:
   setwarp:
      description: Set a new warp point at the location of the player with the given name.
      permission: paidwarp.setwarp
      usage: /setwarp <name>
   delwarp:
      description: Delete the warp point with the given name.
      permission: paidwarp.delwarp
      usage: /delwarp <name>
   listwarps:
      description: List all available warp points.
      permission: paidwarp.listwarps
      usage: /listwarps [page]
   warp:
      description: Warp to the warp point with the given name.
      permission: paidwarp.warp
      usage: /warp <location>
permissions:
    paidwarp.*:
        description: Gives access to all paidwarp commands
        children:
            paidwarp.setwarp: true
            paidwarp.delwarp: true
            paidwarp.listwarps: true
            paidwarp.warp: true
            paidwarp.free: true
    paidwarp.setwarp:
        description: Set new warp points.
        default: op
    paidwarp.delwarp:
        description: Delete warp points.
        default: op
    paidwarp.listwarps:
        description: List warp points.
        default: true
    paidwarp.warp:
        description: Warp to a predefined warp point.
        default: true
    paidwarp.free:
        description: Warping is free.
        default: op